### ISSUE TITLE
genInstall.install('GRCh37', rsync=False, bash=True) gives FileNotFoundError

### ISSUE THREAD

**Issue by burcakotlu** [AlexandrovLab/SigProfilerMatrixGenerator#168]
Dear all, 

I have installed python3.11 on tscc. However running the following commands on tscc 
```
python
>>> from SigProfilerMatrixGenerator import install as genInstall
>>> genInstall.install('GRCh37', rsync=False, bash=True)

```
gives FileNotFoundError/

FINISHED --2023-12-21 06:22:15--
Total wall clock time: 6.1s
Downloaded: 1 files, 781M in 2.5s (317 MB/s)
All reference files have been created.
Verifying and benchmarking installation now...
The given project path does not appear to exist. Please check that the specified path exists before proceeding...
	/home/burcak/anaconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/references/vcf_files/GRCh37_bench/
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/install.py", line 1029, in install
    benchmark(genome, volume=volume)
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/install.py", line 733, in benchmark
    data_new = pd.read_csv(new_matrix_96, sep="\t", header=0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/burcak/anaconda3/lib/python3.11/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/burcak/anaconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/references/vcf_files/GRCh37_bench/output/SBS/GRCh37_bench.SBS96.all'

**Comment by BramLimSJ** [comment]
Same issue working from Sanger. Not sure how to go about it. Any help will be much appreciated. Thanks

**Comment by burcakotlu** [comment]
For now, you can `pip install SigProfilerMatrixGenerator==1.2.19` and try this version of SPMG.

**Comment by BramLimSJ** [comment]
This works. Thank you.

**Comment by mdbarnesUCSD** [comment]
Directories were not showing up in the v1.2.20 pypi release, causing this issue. The benchmark script has been removed in the v1.2.21 release as we move away from writing to the site-packages. Please update to v1.2.21. Thanks!
