### ISSUE TITLE
TypeError: binomtest() got an unexpected keyword argument 'x'

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerMatrixGenerator#183]
Hi,

I ran SigProfilerMatrixGenerator with a binomtest error:

Traceback (most recent call last):
  File "/share/app/bin/SigProfilerMatrixGenerator", line 8, in <module>
    sys.exit(main_function())
  File "/share/app/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator_CLI.py", line 32, in main_function
    controller.dispatch_matrix_generator(args)
  File "/share/app/lib/python3.9/site-packages/SigProfilerMatrixGenerator/controllers/cli_controller.py", line 201, in dispatch_matrix_generator
    mg.SigProfilerMatrixGeneratorFunc(
  File "/share/app/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 1469, in SigProfilerMatrixGeneratorFunc
    matrices = matGen.matrix_generator(
  File "/share/app/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/MutationMatrixGenerator.py", line 3127, in matrix_generator
    pval = stats.binomtest(x=successes, n=total_trials).pvalue
TypeError: binomtest() got an unexpected keyword argument 'x'

THE METADATA ABOUT SYSTEM AND RUNTIME

-------System Info-------
Operating System Name: Linux
Release: 3.10.0-1127.el7.x86_64
Version: #1 SMP Tue Mar 31 23:36:51 UTC 2020

-------Python and Package Versions-------
Python Version: 3.9.4
SigProfilerMatrixGenerator Version: 1.2.26
SigProfilerPlotting version: 1.3.23
matplotlib version: 3.9.0
statsmodels version: 0.14.2
scipy version: 1.13.1
pandas version: 1.5.3
numpy version: 1.26.4

-------Vital Parameters Used for the execution -------
Project: CRC
Genome: GRCh38
Input File Path: ./
exome: False
bed_file: None
chrom_based: True
plot: True
tsb_stat: True
seqInfo: True

-------Date and Time Data-------
Date and Clock time when the execution started: 2024-06-05 16:04:21.233447

-------Runtime Checkpoints-------
Chromosome 16 done

**Comment by mdbarnesUCSD** [comment]
Thanks @YingYa for reaching out about this issue. Please follow updates on #181 as this is a duplicate.
