### ISSUE TITLE
KeyError: 'Simple' when exome = True

### ISSUE THREAD

**Issue by marianaurera** [AlexandrovLab/SigProfilerMatrixGenerator#199]
Hi, I'm trying to run the cosmic_fit() function on maf files but come across the error "KeyError: 'simple'" when I pass the argument `exome = TRUE`. I don't understand what the issue is and would appreciate some help. I'm using the R wrapper for this. Thank you!

For more context, my code looks like this: `cosmic_fit(samples, output, input_type="vcf", genome_build="GRCh38", context_type = "ID",  exome = T, cosmic_version=3.3)`

**Comment by mdbarnesUCSD** [comment]
I have transferred this issue because after initial testing for SigProfilerMatrixGenerator v1.2.29 with ID VCF input files and exome=True the following error occurs (found in the error log from the SigProfilerMatrixGenerator run):

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbarnes/Desktop/AlexandrovLab/Github_Files/2024/SigProfilerAssignment/SigProfilerAssignment/Analyzer.py", line 132, in cosmic_fit
    decomp.spa_analyze(
  File "/Users/mbarnes/Desktop/AlexandrovLab/Github_Files/2024/SigProfilerAssignment/SigProfilerAssignment/decomposition.py", line 308, in spa_analyze
    data = datadump.SigProfilerMatrixGeneratorFunc(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mbarnes/anaconda3/envs/spa_i144/lib/python3.11/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 2404, in SigProfilerMatrixGeneratorFunc
    mutation_ID["simple"],
    ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'simple'

This error does not occur when running the v1.2.28 version of code, therefore this issue pertains to the v1.2.29 release.

**Comment by mdbarnesUCSD** [comment]
Please update to SigProfilerMatrixGenerator v1.2.30 to resolve this issue. Thanks!
