### ISSUE TITLE
"I/O operation on closed file" when using Jupyter-Notebook

### ISSUE THREAD

**Issue by quacksawbones** [AlexandrovLab/SigProfilerMatrixGenerator#39]
I am trying to use a Jupyter Notebook to develop a script 

Unfortunately, when I execute:
`from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
matrices = matGen.SigProfilerMatrixGeneratorFunc("name",
                                                 "GRCh37",
                                                 ".../running_folder",
                                                 plot=False,
                                                 exome=False,
                                                 bed_file=None,
                                                 chrom_based=False,
                                                 tsb_stat=False,
                                                 seqInfo=False,
                                                 cushion=100)`

the cell keeps running, while in the console, I receive the following:
`Traceback (most recent call last):
  File "/home/dcullerne/miniconda3/envs/SigProfiler/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 381, in dispatch_queue
    yield self.process_one()
  File "/home/dcullerne/miniconda3/envs/SigProfiler/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/dcullerne/miniconda3/envs/SigProfiler/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/dcullerne/miniconda3/envs/SigProfiler/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/dcullerne/miniconda3/envs/SigProfiler/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/dcullerne/miniconda3/envs/SigProfiler/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/dcullerne/miniconda3/envs/SigProfiler/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 278, in dispatch_shell
    sys.stderr.flush()
ValueError: I/O operation on closed file.`

Stdout indicates the resulting files are being generated correctly:
`Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 4.08 seconds.
Starting matrix generation for INDELs...Completed! Elapsed time: 3.98 seconds.
Matrices generated for 2 samples with 0 errors. Total of 500 SNVs, 3 DINUCs, and 8 INDELs were successfully analyzed.`

Kernel information:
`Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.`

Notebook server version: 6.1.3

Thankyou.

**Comment by ebergstr** [comment]
This issue should have been fixed in the newest version of the tool. Can you please update the tool (pip install SigProfilerMatrixGenerator --upgrade) and rerun your analysis? Please reopen this issue if the error persists.

Best,
Erik

**Comment by quacksawbones** [comment]
Yep, can confirm, I'm no longer seeing this issue. Thanks 👍
