### ISSUE TITLE
Chromosome MT bug in mouse genome mm39

### ISSUE THREAD

**Issue by sudogene** [AlexandrovLab/SigProfilerMatrixGenerator#74]
When using reference genome "mm39", the tool attempted to read MT chromosome which is not available in the mouse reference.

Error log:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda3/envs/sigprofiler/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 537, in SigProfilerMatrixGeneratorFunc
    mutation_ID, skipped_mut, total = matGen.catalogue_generator_INDEL_single (mutation_ID, lines, chrom, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, exome, genome, ncbi_chrom, limited_indel, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, seqInfo, gs, log_file)
  File ".../anaconda3/envs/sigprofiler/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py", line 748, in catalogue_generator_INDEL_single
    with open (chrom_path + chrom + '.txt', "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../anaconda3/envs/sigprofiler/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/mm39/MT.txt'
```

I believe the `convert_input_to_simple_files.py` functions have not accounted for this new reference genome.
Manually adding checks for "mm39" solves the problem on my end but it would be nice if this is updated for all users.
This issue may also resurface if newer supported reference genomes are released in the future.

Regards,
Andy

**Comment by mdbarnesUCSD** [comment]
Hi @sudogene,

Could you please provide what version you are using? If you are not using v1.2.0, please update and let us know if the issue that you are experiencing still exists.

Thanks!

**Comment by sudogene** [comment]
Yes I'm using v1.2.0, I have also tried it on a new environment. Here's the log

```
Python 3.10.0 (default, Nov 10 2021, 19:16:14) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SigProfilerMatrixGenerator import install as genInstall
>>> genInstall.install('mm39', rsync=False, bash=True)
Beginning installation. This may take up to 40 minutes to complete.
The transcriptional reference data for mm39 has been saved.
All reference files have been created.
To proceed with matrix_generation, please provide the path to your vcf files and an appropriate output path.
Installation complete.
>>> from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
>>> matrices = matGen.SigProfilerMatrixGeneratorFunc("test", "mm39", "strelka2", plot=False, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100)
Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 22.34 seconds.
Starting matrix generation for INDELs...>>> 
>>> import SigProfilerMatrixGenerator
>>> SigProfilerMatrixGenerator.__version__
'1.2.0'
```

The process gets killed when it tries to work on INDELs.
The error log is the same as OP in the sense that it tries to look for chromosomes that do not exist in mm39,
such as 22 and MT. In the log below it's 22, in OP it's MT because I just remembered I tried to remedy 22 before by altering the code. Regardless, it doesn't seem to be forming the `CHROM.txt` correctly for mm39 reference.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda3/envs/test/lib/python3.10/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 532, in SigProfilerMatrixGeneratorFunc
    mutation_ID, skipped_mut, total = matGen.catalogue_generator_INDEL_single (mutation_ID, lines, chrom, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, exome, genome, ncbi_chrom, limited_indel, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, seqInfo, gs, log_file)
  File ".../anaconda3/envs/test/lib/python3.10/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py", line 748, in catalogue_generator_INDEL_single
    with open (chrom_path + chrom + '.txt', "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../anaconda3/envs/test/lib/python3.10/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/mm39/22.txt'
```

Regards

**Comment by mdbarnesUCSD** [comment]
Hi @sudogene,

Thanks for your patience. If you are still experiencing the issue, could you please send over the files via e-mail that cause this issue? You can find my e-mail on the README.

Thank you!

**Comment by monagai** [comment]
Hi, 

I've got the same kind of error with rn6.

Linux
Python 3.9.6
SigProfilerMatrixGenerator 1.2.1
```
Traceback (most recent call last):
....
  File ".../lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 611, in sigProfilerExtractor
    data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,	bed_file=None, chrom_based=False, plot=False, gs=False)
  File ".../lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 532, in SigProfilerMatrixGeneratorFunc
    mutation_ID, skipped_mut, total = matGen.catalogue_generator_INDEL_single (mutation_ID, lines, chrom, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, exome, genome, ncbi_chrom, limited_indel, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, seqInfo, gs, log_file)
  File ".../lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py", line 748, in catalogue_generator_INDEL_single
    with open (chrom_path + chrom + '.txt', "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/rn6/MT.txt'
```

**Comment by monagai** [comment]
Hi,

I've got the same kind of error with rn6.
However, I could do the same thing for mm10 successfully (of course, vcf files differ.)

`.../references/chromosomes/tsb/rn6/MT.txt` is not included in rn6 reference downloaded with SigProfilerMatrixGenerator 1.2.1 genInstall.install() for rn6.

Linux
Python 3.9.6
SigProfilerExtractor		  1.1.4
SigProfilerMatrixGenerator	  1.2.1
sigProfilerPlotting		  1.2.1
sig.sigProfilerExtractor(), input_type='vcf'

```
Traceback (most recent call last):
  ...
  File ".../local/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 534, in sigProfilerExtractor
    data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,	bed_file=None, chrom_based=False, plot=False, gs=False)
  File ".../local/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 532, in SigProfilerMatrixGeneratorFunc
    mutation_ID, skipped_mut, total = matGen.catalogue_generator_INDEL_single (mutation_ID, lines, chrom, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, exome, genome, ncbi_chrom, limited_indel, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, seqInfo, gs, log_file)
  File ".../local/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py", line 748, in catalogue_generator_INDEL_single
    with open (chrom_path + chrom + '.txt', "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../local/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/rn6/MT.txt'
```

**Comment by monagai** [comment]
Here is a follow-up report.

I could aovid this error with placing empty dummy file as `.../local/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/rn6/MT.txt` since my rn6 vcf files don't contain chrMT data.

**Comment by mdbarnesUCSD** [comment]
Please update to v1.2.7 and if you are still encountering this issue please reach out.
