### ISSUE TITLE
Referenev genome (GRCm39) installation error

### ISSUE THREAD

**Issue by Pravithaks** [AlexandrovLab/SigProfilerMatrixGenerator#88]
Beginning installation using locally provided files.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mvrccri/anaconda3/lib/python3.7/site-packages/SigProfilerMatrixGenerator/install.py", line 504, in install
    shutil.unpack_archive(offline_files_path + genome + ".tar.gz", ref_dir + "/references/chromosomes/tsb/")
  File "/home/mvrccri/anaconda3/lib/python3.7/shutil.py", line 993, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/home/mvrccri/anaconda3/lib/python3.7/shutil.py", line 923, in _unpack_tarfile
    tarobj = tarfile.open(filename)
  File "/home/mvrccri/anaconda3/lib/python3.7/tarfile.py", line 1571, in open
    return func(name, "r", fileobj, **kwargs)
  File "/home/mvrccri/anaconda3/lib/python3.7/tarfile.py", line 1636, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/home/mvrccri/anaconda3/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/mvrccri/anaconda3/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCm39.tar.gzGRCm39.tar.gz'

**Comment by ebergstr** [comment]
Hi,

To install supported reference genomes, you need to only include the genome name in the install command. For example:

genInstall.install('GRCm39', rsync=False, bash=True)

Please let us know if this does not resolve your issue.

**Comment by mdbarnesUCSD** [comment]
Hi @Pravithaks,

There was an issue with v1.2.7, so that version has been taken down. Please update to [v1.2.8](https://pypi.org/project/SigProfilerMatrixGenerator/1.2.8/).


Thanks!

**Comment by Pravithaks** [comment]
Hai @mdbarnesUCSD,

I'm still facing the same issue after I installed the new version and @ebergstr suggestion. Please let me know is there any other way to solve this bug.

Thanks!

**Comment by Pravithaks** [comment]
Hello @mdbarnesUCSD,
Please correct me if I'm wrong. As you can see in the **error: No such file directory**. I checked with directory the tool was right there is no such file directory in tsb folder. Instead of that the reference file was present in tsb_BED folder. Why the tool was directed to tsb instead of tsb_BED folder. I think its made default like that. Please let me know, how we could rectify this error.

ERROR:
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SigProfilerMatrixGenerator import install as genInstall
>>> genInstall.install('mm39')
Beginning installation. This may take up to 40 minutes to complete.
tar (child): /home/mvrccri/.local/lib/python3.8/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/mm39.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The ensembl ftp site is not currently responding.

Thanks.

**Comment by mdbarnesUCSD** [comment]
Please refer to issue #27, it looks like there is likely a firewall in place.

Also, if you are still encountering the issue please include the log files from the output directory as well.

Thanks!

**Comment by Pravithaks** [comment]
Hai @mdbarnesUCSD ,

I tried as per your suggestion. Still I'm facing issue like this:
ERROR:
Beginning installation. This may take up to 20 minutes to complete.
[DEBUG] Path to SigProfilerMatrixGenerator used for the install:  /home/mvrccri/.local/lib/python3.8/site-packages/SigProfilerMatrixGenerator
GRCm39 is not supported. The following genomes are supported:
GRCh37, GRCh38, mm10

when I used this code:
>>> from SigProfilerMatrixGenerator import install as genInstall
>>> genInstall.install('GRCm39', ftp=False, bash=True)
Instead of GRCm39, I tried with mm39 a well. 
Please let me know how to rectify this.

I didn't get the log file.

**Comment by mdbarnesUCSD** [comment]
You will want to use "mm39" as the reference genome and it looks like you are having issue with a firewall.

If you are having difficult with the firewall, another option is that you can download the files from the ftp server, move them to the computer you would like to run SigProfilerMatrixGenerator on, and then install by following step 2b from the README.

Here is the wget command for downloading from ftp server:
wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/mm39.tar.gz

**Comment by Pravithaks** [comment]
--2022-07-19 11:50:30--  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/mm39.tar.gz
  (try:17) => ‘mm39.tar.gz’
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|132.249.225.8|:21... failed: Connection timed out.
Retrying.

--2022-07-19 11:52:50--  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/mm39.tar.gz
  (try:18) => ‘mm39.tar.gz’
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|132.249.225.8|:21... failed: Connection timed out.
Retrying.

--2022-07-19 11:55:09--  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/mm39.tar.gz
  (try:19) => ‘mm39.tar.gz’
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|132.249.225.8|:21... failed: Connection timed out.
Retrying.

--2022-07-19 11:57:28--  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/mm39.tar.gz
  (try:20) => ‘mm39.tar.gz’
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|132.249.225.8|:21... failed: Connection timed out.
Giving up.
 The tool is giving up. Not able to download the reference genome.

**Comment by mdbarnesUCSD** [comment]
It looks like you are still downloading from behind a firewall, could you please try downloading on a different computer using a different network?

**Comment by Pravithaks** [comment]
Hai @mdbarnesUCSD,

I downloaded the file manually. And when I tried to install the ref genome, I received this error:
ERROR:
Beginning installation using locally provided files.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mvrccri/.local/lib/python3.8/site-packages/SigProfilerMatrixGenerator/install.py", line 519, in install
    if check_sum[genome][chrom] != check:
KeyError: '3_BED_TSB'

MY CODE was :
from SigProfilerMatrixGenerator import install as genInstall
genInstall.install('mm39', offline_files_path='/home/mvrccri/anaconda3/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/')

**Comment by mdbarnesUCSD** [comment]
offline_files_path is the path to the directory containing the mm39.tar.gz that you downloaded from the ftp server.

It would be like this:
`genInstall.install('mm39', offline_files_path='directory_containg_mm39_tar_gz/')`

**Comment by Pravithaks** [comment]
I still have the same issue after I tried in this way. I downloaded ref genome from the NCBI  assembly not from the ftp server. When i tried to download from the ftp server, it showed failed connection time out. Even after i bypassed the firewall issue. Its having issue with IP address I think. The command which i was run in my workstation able to reach till Github, then it was stuck.

**Comment by Pravithaks** [comment]
Hello @mdbarnesUCSD,
I'm stuck with the issue. I want to rectify this as soon as possible.I informed the issue to Dr.Ludmil Alexandrov through my boss(**Dr.Anu R I**). Could you please help me to find a precise solution for this.

Thanks!

**Comment by Pravithaks** [comment]
Hai,
You can use the below command to install the reference genome of your interest. I have done using this command. All the best.

genInstall.install('GRCh37', offline_files_path='path/to/directory/containing/GRCh37.tar.gz')

**Comment by Glies2** [comment]
I am sorry that I am not familia with Python, I am use SigProflierMatrixGeneraotrR, and the problem is come from Rtudio. So, can you please teach me how to use the command that you have mentioned. Is it used in cmd?
Anyway, I am appreciate. 
Looking forward to you replay.
